/** Host-only C10 v3 client for the Docker loopback-published sidecar. */
import { createPublicKey, generateKeyPairSync, randomUUID, sign, verify } from "node:crypto";
import { C10ReceiptError, canonicalJson, sha256, type ReceiptBinding } from "./contracts.js";
import { BrowserTransport, C10_REVIEWED_BROWSER_ENGINE, type BrowserTrustedEvidence, type InternalBrowserExecutor } from "./browser_transport.js";
import { type RequestCard, type TransportResponse } from "./transport.js";

const PATH = "/internal/c10/v3/browser-execute";
const PROTOCOL = 3 as const;
export interface LocalBrowserFetchResponse { readonly ok: boolean; readonly status: number; json(): Promise<unknown>; text(): Promise<string>; }
export type LocalBrowserFetch = (input: string, init: Readonly<{ method: "POST" | "GET"; headers: Readonly<Record<string, string>>; body?: string }>) => Promise<LocalBrowserFetchResponse>;
export interface C10EphemeralKeyMaterial { readonly coordinatorPrivateKeyPem: string; readonly coordinatorPublicKeyPem: string; readonly sidecarEvidencePrivateKeyPem: string; readonly sidecarEvidencePublicKeyPem: string; }

export function generateEphemeralC10Keys(): C10EphemeralKeyMaterial {
  const coordinator = generateKeyPairSync("ed25519"); const sidecar = generateKeyPairSync("ed25519");
  return Object.freeze({ coordinatorPrivateKeyPem: coordinator.privateKey.export({ type: "pkcs8", format: "pem" }).toString(), coordinatorPublicKeyPem: coordinator.publicKey.export({ type: "spki", format: "pem" }).toString(), sidecarEvidencePrivateKeyPem: sidecar.privateKey.export({ type: "pkcs8", format: "pem" }).toString(), sidecarEvidencePublicKeyPem: sidecar.publicKey.export({ type: "spki", format: "pem" }).toString() });
}
function loopbackServiceUrl(value: string): string { let endpoint: URL; try { endpoint = new URL(value); } catch { throw new C10ReceiptError("C10 browser service URL is invalid"); } if (endpoint.protocol !== "http:" || !["127.0.0.1", "localhost", "[::1]"].includes(endpoint.hostname) || endpoint.username || endpoint.password || endpoint.pathname !== "/" || endpoint.search || endpoint.hash) throw new C10ReceiptError("C10 v3 browser transport must be Docker loopback-only"); return endpoint.toString().replace(/\/$/, ""); }
function record(value: unknown, names: readonly string[]): Record<string, unknown> { if (!value || typeof value !== "object" || Array.isArray(value) || Object.keys(value).sort().join(",") !== [...names].sort().join(",")) throw new C10ReceiptError("C10 v3 sidecar evidence has an invalid schema"); return value as Record<string, unknown>; }
function keyId(publicKeyPem: string): string { return sha256(publicKeyPem); }
function v3Binding(binding: ReceiptBinding, cardSha256: string): Record<string, string> { return Object.freeze({ planSha256: binding.planSha256, cohortSha256: binding.cohortSha256, cardSha256, manifestSha256: binding.policySha256, sessionSha256: binding.implementationSha256, armSha256: binding.armSha256, profileSha256: binding.sourceSha256 }); }
function assertHex(value: unknown, name: string): string { if (typeof value !== "string" || !/^[0-9a-f]{64}$/.test(value)) throw new C10ReceiptError(`${name} is invalid`); return value; }

export class LocalPlaywrightBrowserExecutor implements InternalBrowserExecutor {
  private readonly endpoint: string;
  constructor(endpoint: string, private readonly coordinatorPrivateKeyPem: string, private readonly sidecarEvidencePublicKeyPem: string, private readonly hostTransportKey: string, private readonly fetcher: LocalBrowserFetch = async (input, init) => globalThis.fetch(input, init), private readonly onVerifiedEvidence?: (evidence: BrowserTrustedEvidence) => void) { this.endpoint = loopbackServiceUrl(endpoint); if (hostTransportKey.length < 32) throw new C10ReceiptError("C10 v3 host transport key is unavailable"); }
  async health(): Promise<void> {
    const response = await this.fetcher(`${this.endpoint}/health`, { method: "GET", headers: { "x-firecrawl-host-transport-key": this.hostTransportKey } });
    if (!response.ok) throw new C10ReceiptError("C10 v3 sidecar health is unavailable");
    const payload = record(await response.json(), ["activePages", "configuredCapacity", "coordinatorKeyId", "evidenceKeyId", "healthSignature", "protocolVersion", "replayEntries", "status", "transport"]); const signature = payload.healthSignature; delete payload.healthSignature;
    if (payload.protocolVersion !== PROTOCOL || payload.status !== "healthy" || payload.transport !== "docker-loopback-tcp" || payload.coordinatorKeyId !== keyId(this.coordinatorPublicKey()) || payload.evidenceKeyId !== keyId(this.sidecarEvidencePublicKeyPem) || typeof signature !== "string" || !verify(null, Buffer.from(canonicalJson(payload), "utf8"), this.sidecarEvidencePublicKeyPem, Buffer.from(signature, "base64url"))) throw new C10ReceiptError("C10 v3 sidecar health attestation is invalid");
  }
  private coordinatorPublicKey(): string { return createPublicKey(this.coordinatorPrivateKeyPem).export({ type: "spki", format: "pem" }).toString(); }
  async execute(instruction: Readonly<Parameters<InternalBrowserExecutor["execute"]>[0]>): Promise<TransportResponse> {
    const binding = v3Binding(instruction.binding, instruction.cardSha256); const capability = Object.freeze({ protocolVersion: PROTOCOL, coordinatorKeyId: keyId(this.coordinatorPublicKey()), nonce: randomUUID(), expiresAtMs: Date.now() + Math.min(instruction.card.timeoutMs, 120_000), sourceKey: instruction.card.sourceKey, binding });
    const payload = Buffer.from(canonicalJson(capability), "utf8").toString("base64url"); const authorization = `${payload}.${sign(null, Buffer.from(payload, "utf8"), this.coordinatorPrivateKeyPem).toString("base64url")}`;
    let http: LocalBrowserFetchResponse; try { http = await this.fetcher(`${this.endpoint}${PATH}`, { method: "POST", headers: { "content-type": "application/json", "x-c10-browser-authorization": authorization, "x-firecrawl-host-transport-key": this.hostTransportKey }, body: canonicalJson({ capability, card: instruction.card }) }); } catch { throw new C10ReceiptError("C10 v3 sidecar request failed without fallback"); }
    if (!http.ok) { await http.text().catch(() => ""); throw new C10ReceiptError("C10 v3 sidecar rejected the armed request without fallback"); }
    const raw = record(await http.json(), ["binding", "bodyBase64", "cacheRead", "cacheWrite", "challengeDetected", "configuredCapacity", "contentType", "context", "elapsedMs", "engineAttempt", "evidenceSignature", "finalUrl", "jobId", "leaseEndMonotonicNs", "leaseStartMonotonicNs", "observedActivePages", "pageLease", "protocolVersion", "proxy", "queueMs", "redirectCount", "status"]); const signature = raw.evidenceSignature; delete raw.evidenceSignature;
    if (typeof signature !== "string" || !verify(null, Buffer.from(canonicalJson(raw), "utf8"), this.sidecarEvidencePublicKeyPem, Buffer.from(signature, "base64url"))) throw new C10ReceiptError("C10 v3 sidecar evidence attestation failed");
    const sideBinding = record(raw.binding, ["armSha256", "cardSha256", "cohortSha256", "manifestSha256", "planSha256", "profileSha256", "sessionSha256"]); if (canonicalJson(sideBinding) !== canonicalJson(binding)) throw new C10ReceiptError("C10 v3 evidence binding is contradictory"); const engineAttempt = record(raw.engineAttempt, ["engine", "fallbackDisabled", "fallbackUsed", "ordinal"]); const pageLease = record(raw.pageLease, ["leaseId", "slot"]); const context = record(raw.context, ["cache", "ephemeral", "storageState"]); const body = Buffer.from(String(raw.bodyBase64), "base64");
    if (raw.protocolVersion !== PROTOCOL || engineAttempt.engine !== C10_REVIEWED_BROWSER_ENGINE || engineAttempt.ordinal !== 1 || engineAttempt.fallbackDisabled !== true || engineAttempt.fallbackUsed !== false || raw.cacheRead !== false || raw.cacheWrite !== false || context.ephemeral !== true || context.storageState !== "none" || context.cache !== "disabled-cdp-and-fetch-no-store" || !Number.isInteger(raw.status) || typeof raw.finalUrl !== "string" || (raw.contentType !== null && typeof raw.contentType !== "string") || !Number.isFinite(raw.elapsedMs) || !Number.isInteger(raw.configuredCapacity) || !Number.isInteger(raw.observedActivePages) || typeof pageLease.leaseId !== "string" || !Number.isInteger(pageLease.slot) || typeof raw.leaseStartMonotonicNs !== "string" || typeof raw.leaseEndMonotonicNs !== "string") throw new C10ReceiptError("C10 v3 sidecar evidence is malformed");
    const trustedBrowserEvidence: BrowserTrustedEvidence = Object.freeze({ protocolVersion: PROTOCOL, kind: "cre_capacity_c10_browser_execution_evidence_v3", binding: sideBinding as Record<string, string>, engineAttempt: engineAttempt as BrowserTrustedEvidence["engineAttempt"], pageLease: pageLease as BrowserTrustedEvidence["pageLease"], leaseStartMonotonicNs: raw.leaseStartMonotonicNs as string, leaseEndMonotonicNs: raw.leaseEndMonotonicNs as string, observedActivePages: raw.observedActivePages as number, configuredCapacity: raw.configuredCapacity as number, context: context as BrowserTrustedEvidence["context"], rawResponseSha256: sha256(body), cacheRead: false, cacheWrite: false, source: Object.freeze({ status: raw.status as number, finalUrl: raw.finalUrl as string, contentType: raw.contentType as string | null }) });
    this.onVerifiedEvidence?.(trustedBrowserEvidence);
    return Object.freeze({ status: raw.status as number, finalUrl: raw.finalUrl as string, redirectCount: raw.redirectCount as number, elapsedMs: raw.elapsedMs as number, challengeDetected: raw.challengeDetected as boolean, body, contentType: raw.contentType as string | null, providerAttempts: 1, cacheMode: "no-store", trustedBrowserEvidence });
  }
}
export function createLocalC10BrowserTransport(sourceKey: string, binding: ReceiptBinding, cards: ReadonlyMap<string, RequestCard>, options: Readonly<{ coordinatorPrivateKeyPem: string; sidecarEvidencePublicKeyPem: string; hostTransportKey: string; serviceUrl: string; fetcher?: LocalBrowserFetch; onVerifiedEvidence?: (evidence: BrowserTrustedEvidence) => void }>): BrowserTransport { return new BrowserTransport(sourceKey, binding, cards, new LocalPlaywrightBrowserExecutor(options.serviceUrl, options.coordinatorPrivateKeyPem, options.sidecarEvidencePublicKeyPem, options.hostTransportKey, options.fetcher, options.onVerifiedEvidence)); }
