/** Side-effect-free Colliers request, map, and card-identity helpers for C10. */
import * as cheerio from "cheerio";
export const COLLIERS_SALESTRACKER_BASE = "https://sales.colliers.com";
export const COLLIERS_RCM_BASE = "https://my.rcm1.com";
export const COLLIERS_SOURCE_URL = `${COLLIERS_SALESTRACKER_BASE}/`;
export const COLLIERS_PAGE_SIZE = 100;
export type ColliersMapGroup = { projectId: string; pins: Array<{ latitude: number; longitude: number }> };
const clean = (value: unknown): string | null => typeof value === "string" && value.trim() ? value.trim() : null;
const numberOrNull = (value: unknown): number | null => typeof value === "number" && Number.isFinite(value) && value !== 0 ? value : null;
export function colliersHeaders(accept = "application/json, text/javascript, */*; q=0.01"): Record<string, string> { return { accept, origin: COLLIERS_SALESTRACKER_BASE, referer: COLLIERS_SOURCE_URL, "user-agent": "Mozilla/5.0 CRE collector", "x-requested-with": "XMLHttpRequest" }; }
export function colliersListUrl(engineKey: string, start: number, pageSize: number): string { return `${COLLIERS_RCM_BASE}/api/AjaxEngine/GetListingsHtml?pv=${encodeURIComponent(engineKey)}&Start=${start}&PageSize=${pageSize}`; }
export function colliersMapUrl(engineKey: string, start: number, pageSize: number): string { return `${COLLIERS_RCM_BASE}/api/AjaxEngine/GetMapData?pv=${encodeURIComponent(engineKey)}&Start=${start}&PageSize=${pageSize}`; }
export function colliersSlpInitUrl(pv: string): string { return `${COLLIERS_RCM_BASE}/api/handler/slp/Init?pv=${encodeURIComponent(pv)}`; }
export function groupColliersMapLocations(rows: any[]): ColliersMapGroup[] { const groups = new Map<string, ColliersMapGroup>(); for (const [index, row] of rows.entries()) { const raw = row?.ProjectId ?? row?.projectId; if (raw === null || raw === undefined || !String(raw).trim()) throw new Error(`Colliers map row ${index} is missing ProjectId`); const projectId = String(raw).trim(); const group = groups.get(projectId) ?? { projectId, pins: [] }; groups.set(projectId, group); const latitude = numberOrNull(Number(row?.Latitude ?? row?.latitude)); const longitude = numberOrNull(Number(row?.Longitude ?? row?.longitude)); if (latitude !== null && longitude !== null && latitude >= -90 && latitude <= 90 && longitude >= -180 && longitude <= 180 && !group.pins.some((pin) => pin.latitude === latitude && pin.longitude === longitude)) group.pins.push({ latitude, longitude }); } return [...groups.values()]; }
export function parseColliersReceiptCards(html: string, groups: readonly ColliersMapGroup[], start: number): Array<{ mapProjectId: string; detailPv: string | null; detailUrl: string | null }> { const $ = cheerio.load(html); const cards: Array<{ mapProjectId: string; detailPv: string | null; detailUrl: string | null }> = []; $("li.item").each((index, element) => { const card = $(element); if (!clean(card.text())) return; const group = groups[index]; if (!group) throw new Error(`Colliers card ${start + index} has no ordered ProjectId map group`); const raw = card.find('a[href*="landing.aspx"], a[href*="modern.aspx"], a[href*="/slp/"]').first().attr("href"); let detailUrl: string | null = null; try { detailUrl = raw ? new URL(raw, COLLIERS_RCM_BASE).toString() : null; } catch { detailUrl = null; } const detailPv = detailUrl ? new URL(detailUrl).searchParams.get("pv") : null; cards.push({ mapProjectId: group.projectId, detailPv, detailUrl }); }); if (cards.length !== groups.length) throw new Error(`Colliers parsed-card/map-group parity failed at start ${start}: ${cards.length} != ${groups.length}`); return cards; }
export function colliersAssertDetailProjectId(mapProjectId: string, detailProjectId: unknown): string { if (detailProjectId === null || detailProjectId === undefined || !String(detailProjectId).trim()) throw new Error(`Colliers SLP detail for map ProjectId ${mapProjectId} omitted ProjectId`); const actual = String(detailProjectId).trim(); if (actual !== mapProjectId) throw new Error(`Colliers grouped map/detail ProjectId mismatch: ${mapProjectId} != ${actual}`); return actual; }
