/** Side-effect-free Marcus request and response helpers shared with C10. */
export const MARCUS_BASE = "https://www.marcusmillichap.com";
export const MARCUS_PROPERTIES_URL = `${MARCUS_BASE}/properties`;
const clean = (value: unknown): string | null => typeof value === "string" && value.trim() ? value.trim() : null;
export function marcusHeaders(): Record<string, string> { return { accept: "application/json, text/javascript, */*; q=0.01", "content-type": "application/json", origin: MARCUS_BASE, referer: MARCUS_PROPERTIES_URL, "user-agent": "Mozilla/5.0 CRE collector" }; }
export function marcusSearchBody(pageSize: number): Record<string, unknown> { return { pageNumber: 1, pageSize, sortOrder: "DESC", indexFieldName: "orderdate", facets: [], rangeFacets: [], geoFacet: { Polygons: [], Circles: [], FieldName: "customdraw" }, savedSearchId: null, allowedFacets: ["propertytype", "location", "advisors", "listingprice", "caprate"] }; }
export function marcusMapDetailBody(activityId: string): Record<string, unknown> { return { activityId }; }
export function marcusUrl(href: string | null | undefined): string | null { const value = clean(href); if (!value) return null; try { return new URL(value, MARCUS_BASE).toString(); } catch { return null; } }
export function parseMarcusPropertiesResponse(search: any, strict = true): { rows: any[]; total: number | null } { const results = search?.Results ?? search; if (strict && (!results || typeof results !== "object" || Array.isArray(results) || !Array.isArray(results.Properties))) throw new Error("Marcus & Millichap properties response has no Properties array"); const rows = Array.isArray(results?.Properties) ? results.Properties : []; const total = typeof results?.TotalCount === "number" ? results.TotalCount : null; if (strict && (!Number.isFinite(total) || !Number.isInteger(total) || (total as number) < 0)) throw new Error("Marcus & Millichap properties response requires a finite nonnegative integer TotalCount"); if (strict && (total as number) < rows.length) throw new Error(`Marcus & Millichap properties response TotalCount ${total} is below returned rows ${rows.length}`); return { rows, total }; }
export function parseMarcusMapRowsResponse(map: any, strict = true): any[] { const results = map?.Results ?? map; if (strict && (!results || typeof results !== "object" || Array.isArray(results) || !Array.isArray(results.Properties))) throw new Error("Marcus & Millichap mapproperties response has no Properties array"); const rows = Array.isArray(results?.Properties) ? results.Properties : Array.isArray(results) ? results : []; const seen = new Set<string>(); return rows.filter((row: any) => { const activityId = clean(row.ActivityId); if (!activityId || seen.has(activityId)) return false; seen.add(activityId); return true; }); }
